stages:
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
    - when: never

variables:
  KEYCLOAK_VERSION: "20.0.2"

default:
  tags:
    - oss
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure

publish all-in-one docker:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  tags:
    - oss
    - docker
  script:
    - |
      # Build registry URIs.
      registry_uri="$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"

      docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"

      echo "Building tharsis all-in-one docker image"
      docker build -t $registry_uri:latest --build-arg kcversion=$KEYCLOAK_VERSION --no-cache .

      echo "Tagging and pushing image as latest"
      docker image push $registry_uri:latest
